### ISSUE TITLE
Make distributable (installer)

### ISSUE THREAD

**Issue by markusgumbel** [informatik-mannheim/Moduro-Toolbox#38]
The moduro toolbox should be executable w/o having an IDE and w/o compiling the code. A distributable (jar-file?) is required. Probably from Maven.

**Comment by markusgumbel** [comment]
Maven creates distributable moduro-toolbox-0.1-jar-with-dependencies. However, running leads to this error:
```
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Location is not set.
        at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
```

**Comment by markusgumbel** [comment]
Done.
